### PR TITLE
Add one-click hosting option

### PR DESCRIPTION
**Pull request by m3nu**
This adds the one-click hosting option mentioned in the README. Will use the official Docker image, once it's available.

About [PikaPods](https://www.pikapods.com): We just finished our beta program and focus on making privacy-conscious open source apps more accessible. Currently our app store offers around 50 apps and we run around 1500 pods. Currently there are 2 different regions, US and EU, with a third in Hong Kong joining soon. Users always have full access to their data over SFTP. We only sell hosting, so there are no ads, trackers or other limitations.

Button [preview](https://github.com/m3nu/actual-server/tree/add-single-click-hosting#one-click-setup)

### CODE REVIEW

**Comment by jlongster** [comment]
@m3nu cool! I might tweak this and list one-click options under a list because there are a couple. And then see how they play out and which one is favored before blessing it.

One question: how do you update it? If we push out a new version of actual-server, is there a way to update?

**Comment by m3nu** [comment]
Thanks for considering. Could also make sense to merge this with the more technical deployment options, like fly.io below.

We review and test updates manually based on each project’s release feed. Only after some basic tests is a new update rolled out to all pods. This avoids pushing a bad update or missing a breaking change or migration step.

**Comment by jlongster** [comment]
One thing to note is right now the server isn't versioned. We should probably get to that, but there's a lot less changes that go into this code so it's not as high priority.

**Comment by jlongster** [comment]
@m3nu I'll be honest: I'm hesitant to bless your solution yet because we'll have to field reports coming in about it and I don't know anything about this.

Can you change this PR so it's more of a footnote? Here's what you should do:

* Create a new section _below_ the "Deployment" section (near the bottom) called "One-click hosting solutions"
* Create a list of items and a add PikaPods as one item in the list. We'll add more soon

To be honest: fly is our preferred hosted solution right now. They are also working on a one-click workflow, and when we get that set up we are likely to bless that.

If don't here back from you soon, I'll close this PR

**Comment by m3nu** [comment]
Fly.io is for programmers, as are similar platforms, like Heroku or Digital Ocean. I'm sure fly.io is great, but there might be people who don't know how to "install the flyctl utility". 😬 PikaPods is meant for them and deals with details like testing updates, doing backups, etc. It's also meant to monetize FOSS projects by sharing revenue and offering sponsorship tiers. So it's more like an app store for FOSS than an app-neutral PaaS.

I took a shot at re-arranging the deployment section [here](https://github.com/m3nu/actual-server/tree/add-single-click-hosting). As you can see the fly.io section is like 1 page of instructions, if you don't want to loose your data during each update. Maybe it's your favorite platform for running JS code, but you are severely limiting your audience by calling this a "preferred option".

As an aside, since I added Actual to our store, around 10 people already started using it. That's after like a day. We also do a monthly newsletter which always has 3 "featured" apps. I can add it there next month with a little bit of backstory.

**Comment by jlongster** [comment]
Need to think long-term. fly is best-in-class and they are working on a one-click deployment workflow so that's what I plan on blessing to be honest. They've gained my trust in multiple ways. I'm sure your platform is good! And I'm fine linking out to it, but I need to vet what we are linking out to. I already have trust in fly technically and user experience-wise.

I'm OK that they don't have a one-click deployment yet but I'm working with them to set it up.

I was a little confused trying to PikaPod link to run Actual. After signing in, this is all I see:

Screen Shot 2022-05-03 at 1 55 56 PM

I have to search for Actual to find it. That's confusing.

I don't mean to be negative about your platform! I bet you'll fix the above UX issue, and already have a great community. I'm happy to include it. But I always take things slowly and like to thoroughly vet everything that ends up in Actual, including all the things that we tell users to do. This approach is what has built a lot of trust with my users. I'm not really singling out your platform either; if _anybody_ wanted to link to theirs I'd approach them the same way. (Fly has special treatment because indeed, I already have a trusted relationship with them)

I'll check out this PR soon! (at work right now)

**Comment by m3nu** [comment]
Thanks again for considering. No hurry.

You will need to be logged in to get directly to the launch dialog.

**Comment by jlongster** [comment]
I am logged in! No matter what it doesn't pop up for me?

**Comment by m3nu** [comment]
Oh. I think you found a race condition there. Should be fixed now and couldn't trigger it any more. I initially built the feature to run apps from /apps where the the list of apps was already there. The one-click button is pretty new.

I also set the app-to-run to be preserved across login and registration. Probably also nice for users looking for a single app.

**Comment by m3nu** [comment]
Some more improvements for the one-click feature: One will now see the selected app on the login form. Also added the monthly price there for more transparency. [Example](https://www.pikapods.com/pods?run=actual)

BTW: Asians seem to like the app. Seeing a bunch of Chinese and Japanese domains mapped here.

**Comment by jlongster** [comment]
I did end up merging something similar to this, and maybe I should have opened a new PR, sorry. I pulled in your commits and cleaned it up some more and there's a link to it at the bottom of the readme. Thanks!

**Comment by m3nu** [comment]
Great! Will also move to use the official Docker image, once it's available. We're at about two dozen pods running Actual by now.

If you like, I'll introduce it in our monthly newsletter. Goes to about 2000 active PikaPods users. Maybe with some background on why you started the project and what's the vision for it.

**Comment by jlongster** [comment]
@m3nu sounds good to me! are you saying you want me to write that part?

**Comment by m3nu** [comment]
> Maybe with some background on why you started the project and what's the vision for it.

No no. Just a few pointers or bullet points would be great. I'll do the writing. Whatever you want to emphasize.

Here just some examples from last month:

> ### PhotoPrism [»](https://photoprism.app/)
> One of the first apps we added. It allows you to organize and share your photo collection mostly automatically. By keeping the data in open formats and under your control, memories are preserved for the future. The Berlin-based project is fully self-funded and independent. In fact they just incorporated and are working hard to ensure the long-term sustainability of the project.
> 
> ### ListMonk [»](https://listmonk.app/)
> Another exciting project, this time from India. It's best described as a simpler open source version of Mailchimp. It includes scalable subscriber management for millions of recipients, a powerful templating language for dynamic emails and even support for SMS and other messengers. Being free and open source, the subscriber data stays under your control and you are free to add or suggest improvements.
> 
> ### Rallly (yes, 3 Ls) [»](https://rallly.co/)
> This month's newcomer was published less than 3 weeks ago by Luke from the UK. It offers a free and open alternative to Doodle, the meeting scheduling tool. Simply suggest different meeting times and ask your friends or colleagues to choose one. Helps schedule meetings without distraction or upselling.

**Comment by m3nu** [comment]
Hi again, @jlongster.

Newsletter will go out in a few days. Here the text I wrote up for Actual. From what I read, the mobile apps could use maintainers. Is this still the case? If so, I'll include this too and maybe the right person reads it.

### Actual [»](https://actualbudget.com/)
Actual is a privacy-focused personal finance app to keep track of your finances. Published by James from the US. You can host the server part on PikaPods and sync it with available mobile apps or use it via the built-in web interface. The project has rapidly gained in popularity in just a few weeks and many people have already contributed to it. From what I hear, there is still a need to maintain mobile apps for different platforms. If you are interested in stepping up, simply get in touch with James over [Github](https://github.com/actualbudget/actual).

**Pull request closed without merging**
