### PR TITLE
feat: add 'SEB Kort Bank AB' credit card support

### PR DESCRIPTION
**Pull request by walleb**
Add custom bank adapter for 'SEB Kort Bank AB' to properly sync credit card transactions.

* Flip transaction amount so purchases are listed as payments (related to #261 )
* Handle that SEB is sending the creditor name in additionalInfo (copied from #316)
* Balance calculation based on 'expected' balance type

### CODE REVIEW

**Comment by MatissJanis** [comment]
👋 Just checking if you're still working here or if this is ready for review. The PR is in "draft".

**Comment by walleb** [comment]
Yes, still working on it. I put it into "draft" as a realized that I need to verify the balance calculation. I suspect that it now shows a positive amount when it should be negative. Tricky to get it right for credit card accounts...

**Comment by walleb** [comment]
Yes, still working on it. I put it into "draft" as a realized that I need to verify the balance calculation. Balance calculation should be OK now for total, cleared and uncleared balances. It works properly when booking a payment of credit card bill with payee as one of the other accounts.

**Review by MatissJanis — APPROVED** [review]
Thanks

**Pull request merged**
