### PR TITLE
Added easy directable url in actual budget

### PR DESCRIPTION
**Pull request by fzn0x**
Use the `open` package and modify the hostname from 0.0.0.0 to localhost to allow open default browser by default.

The projects are used to filter docker and anything else so there is no memory leak possibility if you run the server on a non-desktop environment. Reference: https://github.com/sindresorhus/open/blob/main/index.js.

### CODE REVIEW

**Comment by fzn0x** [comment]
Thanks for the amazing work you put in and make this open source!

**Comment by jlongster-stripe** [comment]
Thanks! I don't love these change tbh; I don't love servers that pop open a browser automatically. Half the time it gets in the way and is distracting when I'm trying to multi-task. Also we explicitly changed it from `localhost` to `0.0.0.0` so it works on all ips in another PR.

I'm going to close this, but if a lot of other people want it we can reconsider. Want to keep things simple if we can.

**Comment by jlongster** [comment]
Oops, posted from my work account!

**Comment by fzn0x** [comment]
> Oops, posted from my work account!

Haha, thanks for your respond I appreciate it

**Pull request closed without merging**
