### PR TITLE
Add ability to disable password

### PR DESCRIPTION
**Pull request by xethlyx**
This pull request adds the ability to disable passwords. This allows for using software such as [OAuth2 Proxy](https://github.com/oauth2-proxy/oauth2-proxy) or [Authelia](https://github.com/authelia/authelia) as a front-end to integrate with existing SSO solutions easily.

This depends on the related pull request actualbudget/actual#162.

### CODE REVIEW

**Comment by tylerhunt** [comment]
Should this use an environment variable like `ACTUAL_DISABLE_PASSWORD` instead of the more generic `DANGEROUS_DISABLE_PASSWORD`?

**Comment by xethlyx** [comment]
I've named it as such since disabling the password on an inconfigured internet connected server would be a recipe for disaster. If you feel `ACTUAL_DISABLE_PASSWORD` is more fitting though I can charge it.

**Comment by maxerbox** [comment]
I think you should, I agree with Tyler

**Comment by MatissJanis** [comment]
👋 Sorry, but closing this PR.

A bit more context and discussions in the other PR: https://github.com/actualbudget/actual/pull/162

**Pull request closed without merging**
