### PR TITLE
Build and publish images with Github Actions

### PR DESCRIPTION
**Pull request by solidassassin**

### CODE REVIEW

**Comment by solidassassin** [comment]
No configuration needed from the repository owner, since ghcr integrates nicely with GitHub.

**Comment by themegaphoenix** [comment]
@solidassassin is this the same as #11?

**Comment by themegaphoenix** [comment]
The repo maintainer closed the pr #24  in favour of #11 to host on dockerhub

**Comment by jlongster** [comment]
I don't have strong opinions here.

@Kovah @hasanhakkaev Want to explain more about why you favored dockerhub?

**Comment by jlongster** [comment]
Can/should we do both?

**Comment by hasanhakkaev** [comment]
@jlongster It's widely used popular go-to Docker registry for public usage. It's the default registry for Docker cli.
No authentication needed, whereas ghcr requires you do authenticate for pulling.
From a user perspective: 
`docker run nginx:latest` <- nginx image hosted on DockerHub
`docker pull ghcr.io/hasanhakkaev/docker-ghost-ai:latest` <- an image I host in my ghost-docker-ai repo

Those are just things that came to my mind at the moment.Sure there might be other facts.

**Comment by jlongster** [comment]
Ok, let's please consolidate this work in #11 so we have a single thread to follow. @solidassassin can you work with them in there and discuss the change?

**Comment by jlongster** [comment]
Moving to https://github.com/actualbudget/actual-server/pull/11

**Pull request closed without merging**
