### PR TITLE
[WIP] Use express builtin 'trust proxy'

### PR DESCRIPTION
**Pull request by djm2k**
### Changes made
- Added `quote_type = single` to `.editorconfig` (VSCode kept changing them all to double).
- Adjust the `trustedProxies` config option to work with [expressjs](https://expressjs.com/en/guide/behind-proxies.html).
- Remove the `validateAuthHeader` function and check.

### Reasoning
- https://github.com/actualbudget/actual-server/pull/312 introduced `validateAuthHeader` which attempted to re-implement logic provided by expressjs itself through `app.set('trust proxy')` (see docs above)

### Linked
- Fixes https://github.com/actualbudget/actual-server/issues/392
- Related to https://github.com/actualbudget/actual-server/issues/371
- Supersedes https://github.com/actualbudget/actual-server/pull/379

### Ongoing work
- [ ] E2E tests or manual testing to confirm working in different contexts i.e. `trustedProxies` set to:
  - [ ] `1` with Traefik/Caddy
  - [ ] `2` with NGINX and Cloudflare proxies
  - [ ] `10.0.0.0/16,0.233.192.169/32` for manual IP address/subnet CSV
  - [ ] `false` to throw `ERR_ERL_UNEXPECTED_X_FORWARDED_FOR` when a proxy header is detected (current behaviour)
  - [x] `true` to throw `ERR_ERL_PERMISSIVE_TRUST_PROXY` 
- [ ] PR for https://github.com/actualbudget/docs explaining the env var better and linking to the express docs

### CODE REVIEW

**Comment by djm2k** [comment]
This still needs to be debugged, I am getting this error now after these changes: (implying `trustedProxies` is coming through as `true` instead of the default array)
```
ValidationError: The Express 'trust proxy' setting is true, which allows anyone to trivially bypass IP-based rate limiting. See https://express-rate-limit.github.io/ERR_ERL_PERMISSIVE_TRUST_PROXY/ for more information.
    at _Validations.<anonymous> (file:///app/node_modules/express-rate-limit/dist/index.mjs:134:15)
    at _Validations.wrap (file:///app/node_modules/express-rate-limit/dist/index.mjs:287:18)
    at _Validations.trustProxy (file:///app/node_modules/express-rate-limit/dist/index.mjs:132:10)
    at Object.keyGenerator (file:///app/node_modules/express-rate-limit/dist/index.mjs:515:19)
    at file:///app/node_modules/express-rate-limit/dist/index.mjs:569:32
    at async file:///app/node_modules/express-rate-limit/dist/index.mjs:550:5 {
  code: 'ERR_ERL_PERMISSIVE_TRUST_PROXY',
  help: 'https://express-rate-limit.github.io/ERR_ERL_PERMISSIVE_TRUST_PROXY/'
}
```

**Comment by djm2k** [comment]
@twk3 I am very confused by the different terms. What you're describing is known to me as "Trusted IP Ranges" or "IP Authentication". Handling this at the express middleware level instead of in the reverse proxy config seems like a mistake which could lead to future admins misconfiguring their setups.

My previous experience with header authentication has been to set a specific header to a secret value, and ensure that header was cleared from user's requests by the reverse proxy before being set. 

This could be handled by `validateAuthHeader` where it would check the header is present and it's value matches the secret key set in the config.

I'd like to setup an E2E test which covers your use-case as well. For me- the whole app is wrapped in Authelia no matter if i am accessing it locally or externally.

Let me know what you think

**Comment by twk3** [comment]
> @twk3 I am very confused by the different terms. What you're describing is known to me as "Trusted IP Ranges" or "IP Authentication". Handling this at the express middleware level instead of in the reverse proxy config seems like a mistake which could lead to future admins misconfiguring their setups.
> 
> ~My previous experience with header authentication has been to set a specific header to a secret value, and ensure that header was cleared from user's requests by the reverse proxy before being set.~
> 
> ~This could be handled by `validateAuthHeader` where it would check the header is present and it's value matches the secret key set in the config.~ Nevermind, looking at #312 again, this is implemented with `x-actual-password`
> 
> I'd like to setup an E2E test which covers your use-case as well. For me- the whole app is wrapped in Authelia no matter if i am accessing it locally or externally.
> 
> Let me know what you think

Yeah, sorry. That was my fault for using trusted proxy as the name. Should have been `allowedAuthCIDRs` or something like that. And it SHOULD only need to be set if someone wants to lock header auth to a specific endpoint.

To fix the naming situation, we probably need to rename the current impl to `allowedAuthCIDRs`, but populate it by default with whatever folks have set in their `trustedProxies` (to maintain support for the config syntax that we released). But primarily start using trustedProxies for what you have here. (we also need to fix the current implementation so it's not needed to be set if folks just want header auth, without restricting it)

**Comment by dm-canteen** [comment]
Still WIP

**Comment by djm2k** [comment]
Still WIP https://github.com/djm2k/actual-server/commits/add-e2e-test/

**Comment by KiARC** [comment]
This *really* needs to be reopened, it's been two months and Actual still cannot deploy behind a proxy. What is actually needed to move this along?

**Comment by djm2k** [comment]
@KiARC 
> This _really_ needs to be reopened, it's been two months and Actual still cannot deploy behind a proxy. What is actually needed to move this along?

twk3 has generously taken the above discussion and worked it into changes in [`twk3/fix-auth-header-trust`](https://github.com/actualbudget/actual-server/tree/twk3/fix-auth-header-trust) relating to https://github.com/actualbudget/actual-server/issues/371

Would you like to test the above and report back in https://github.com/actualbudget/actual-server/issues/392?

Please check the repo's activity in the future: https://github.com/actualbudget/actual-server/activity

I will continue working on my [`add-e2e-test`](https://github.com/djm2k/actual-server/tree/add-e2e-test) branch when i get the chance

**Pull request closed without merging**
