### PR TITLE
:bug: (asn-bank) add special ASN Bank integration to patch whitespace issue

### PR DESCRIPTION
**Pull request by MatissJanis**
Patch for: https://github.com/actualbudget/actual/issues/2495

### CODE REVIEW

**Comment by kyrias** [comment]
I wonder if we should really perform this unconditionally though, since I don't think there's any valid case in which we'd want to accept such a transaction ID.

**Comment by MatissJanis** [comment]
> I wonder if we should really perform this unconditionally though, since I don't think there's any valid case in which we'd want to accept such a transaction ID.

Generally I agree with you. But see the conversation here: https://github.com/actualbudget/actual/issues/2495

The author is arguing that empty transaction IDs are expected. And since I don't have access to this bank to actually test things - I'll take his word for this.

We can always change this in the future

**Comment by kyrias** [comment]
Well that's quoting yourself and not the author.  :p

But well, fair enough.  Though I'd argue that if we're worried about this being a breaking change at all then it's still possible for this to be a breaking change for other kinds of transactions for the same bank.  Arguably this should instead be reported to GoCardless to be fixed up by them removing the transaction ID if this case happens.

**Comment by MatissJanis** [comment]
> [..] as an optional but _unique_ identifier [..]

Would you mind linking to the docs where they state this? If this is the case, then it does make much more sense to report it to GoCardless and get it patched on their end.

**Comment by kyrias** [comment]
> | transactionId | Max256Text | Optional | Unique transaction identifier given by financial institution |
— https://developer.gocardless.com/bank-account-data/transactions

**Comment by MatissJanis** [comment]
Thanks! I'll revert this back to OP in the github issue and close this PR for now. Lets see if we can get GoCardless to patch this on their end.

**Pull request closed without merging**
