### PR TITLE
Plaid Integration

### PR DESCRIPTION
**Pull request by katrovman**
This PR adds Plaid integration in conjunction with the accompanying PR for actual.

- Added plaid sqlite file to store various fields and data for the Plaid integration between client and server.
- Uses three environment variables: PLAID_CLIENT_ID, PLAID_SECRET, and PLAID_ENV. These are needed to create the Plaid object on the server side.
- Full Plaid flow between client and server for authentication, accounts and transitions syncing.

I am sure there are more efficient ways to handle the various additions and modifications, however my main goal was to use what was already created to complete this process.

It is again important to note that this must be used in combination with the Plaid Integration PR on actual-server. Otherwise this will not operate in either environment.

### CODE REVIEW

**Comment by AIndoria** [comment]
It does say "Work in progress" but I'm curious if it actually works, even at a cursory level if I merge it to a fork (or alternatively, download your fork)?

**Comment by AIndoria** [comment]
Whatever happened to this?

**Comment by szethh** [comment]
I would be interested in this as well

**Comment by rh535** [comment]
Me as well!

**Comment by miniminne** [comment]
Not to beat on a dead horse, but I would love to +1 this to get Plaid integration!

**Comment by culpeppers** [comment]
Hey all, sorry it has taken so long. Life has gotten in the way for a while now. I plan on starting from scratch on this, considering how much has changed.

**Comment by j-f1** [comment]
Glad to to hear that! Check out https://github.com/actualbudget/actual/issues/737 and consider reaching out to @babsher to see if you can come up with a reasonable bank syncing abstraction that can work well with multiple providers.

**Pull request closed without merging**
