### PR TITLE
🐛 Fix existing sessions when using the latest version with Openid

### PR DESCRIPTION
**Pull request by lelemm**
This custom introduced a problem where users after updating the server will have to login again.

This also fix the header authentication that was broken

### CODE REVIEW

**Comment by lelemm** [comment]
I had some time to test it.
How to reproduce:

```bash
git checkout v24.11.0
rm -rf server-files
rm .migrate
yarn install
yarn start
```

**Review by jfdoming — APPROVED** [review]
Tested locally, works as you mentioned. Thanks!

**Review by jfdoming — COMMENTED** [review]
Changes LGTM but let's wait for another maintainer to test

**Review by matt-fidd — APPROVED** [review]
Changes LGTM too

**Comment by lelemm** [comment]
> Tested locally and this patches it for me! Thank you @lelemm
> 
> (and apologies for taking so long again to review.. I have a baby on the way so my calendar lately is quite packed)

I feel you, gratz on the baby :)

**Comment by lelemm** [comment]
@MatissJanis there is still this: https://discord.com/channels/937901803608096828/1310791130492702740
Not sure how it happened. its like the person executed the migration twice

**Pull request merged**
