### PR TITLE
add integration tests for the `/sync` endpoint

### PR DESCRIPTION
**Pull request by tcrasset**
~Needs https://github.com/actualbudget/actual-server/pull/421 to be merged first.~

Ready to be reviewed!

### CODE REVIEW

**Comment by tcrasset** [comment]
@matt-fidd Would you mind reviewing, please?

**Review by MatissJanis — APPROVED** [review]
Thanks! Always nice to see PRs raising the test coverage!

**Comment by MatissJanis** [comment]
(I'll leave this for @matt-fidd to review and merge since he was explicitly mentioned) ;)

**Review by matt-fidd — APPROVED** [review]
LGTM, thanks for this!
Thanks Matiss ;) I assume it's because I was around to review the earlier ones

**Pull request merged**
