### PR TITLE
Instructions for running via Docker

### PR DESCRIPTION
**Pull request by ajtrichards**
I thought i'd add some instructions for getting up and running with the `Dockerfile` that's in the repo

### CODE REVIEW

**Comment by brtwrst** [comment]
You might want to include a mount of the /data dicrectory to enable data persistance

**Comment by jlongster** [comment]
Good call about `/data` -- how would that look here? Can you update it?

**Comment by avioli** [comment]
Usually something like:

```sh
mkdir ./data
docker run -p 5006:5006 -v "$(pwd)/data":/data actual-server
```

Depending on throughput above method might have certain slowdowns, since it will be transferring data over the bridge to the host's file system.

An alternative would be to use `docker volume` as described here: https://docs.docker.com/storage/volumes/#create-and-manage-volumes and use `docker run ... --mount source=myvolume,target=/data ...`

Backing up the latter is described on the same page as above: https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes

**Comment by jlongster** [comment]
Will merge this for now. We can iterate!

**Pull request merged**
