### PR TITLE
docs(engines): add node version in package.json engines

### PR DESCRIPTION
**Pull request by 0rnella**
Per issue #151 , adding a node version to package.json engines!
This should be cleaned up once better-sqlite3 is upgraded to 8.x.x

### CODE REVIEW

**Comment by j-f1** [comment]
The check failures will be fixed by https://github.com/actualbudget/actual-server/pull/153

**Comment by MatissJanis** [comment]
Is this still relevant after v23.3.0 release? https://github.com/actualbudget/actual-server/pull/154

**Comment by 0rnella** [comment]
Hmm, keeping an older major version of a @types package around does sound a bit icky to me, since there's been breaking changes, but looking at the actual usage of it, I wonder if it's even needed at all? 
Anyway, yes, this release does make this PR unnecessary :)

**Comment by MatissJanis** [comment]
> Hmm, keeping an older major version of a @types package around does sound a bit icky to me, since there's been breaking changes, but looking at the actual usage of it, I wonder if it's even needed at all? Anyway, yes, this release does make this PR unnecessary :)

Good point. We might consider cutting it :)

Anyways - sorry that we had to close this PR. But thanks for the help nonetheless! And thanks for adding node 19 support to better-sqlite3!

**Comment by 0rnella** [comment]
No worries, the PR was a band-aid, I'm happy that a better solution was found and it can be closed!

**Pull request closed without merging**
