### PR TITLE
add FilesService

### PR DESCRIPTION
**Pull request by tcrasset**
Related to #420 

The followup PR #432 will actually use this service to refactor much of `app-sync.js`.

### CODE REVIEW

**Comment by tcrasset** [comment]
@matt-fidd Would you mind reviewing, please?

**Comment by matt-fidd** [comment]
Thanks for this! It all seems reasonable to me.

@MatissJanis will be better placed than me to give this the final seal of approval, he's far more knowledgable than me about how the syncing works - so in this case I'll leave it for him to review/merge 😄

**Comment by MatissJanis** [comment]
It will be more meaningful to review #420  instead of this PR since the logic introduced here is not used anywhere.

Lets close this one off and open up #420 (once it's available).

**Comment by tcrasset** [comment]
> It will be more meaningful to review #420 instead of this PR since the logic introduced here is not used anywhere.
> 
> Lets close this one off and open up #420 (once it's available).

I think you meant #432? #420 is just a general (one sided :grin:) discussion about the need for this refactor. I guess Discord (which I joined this morning) is more appropriate for such a discussion. 

I will clean #432 up and have it ready for review :)

**Comment by MatissJanis** [comment]
Yea, my bad. I meant #432!

**Comment by tcrasset** [comment]
Add discussed, all code was moved to #432

**Pull request closed without merging**
