### PR TITLE
[WIP] Update mbank-retail-brexplpw.js

### PR DESCRIPTION
**Pull request by vrozaksen**
Fix linking accounts for mBank Retail Poland.

obraz

### CODE REVIEW

**Comment by MatissJanis** [comment]
👋 Would you mind adding a release notes file? Then I could merge it in time for the next release.

**Comment by vrozaksen** [comment]
> 👋 Would you mind adding a release notes file? Then I could merge it in time for the next release.

Ye, i will do

**Comment by vrozaksen** [comment]
> 👋 Would you mind adding a release notes file? Then I could merge it in time for the next release.

Done :)

**Review by MatissJanis — APPROVED** [review]

**Comment by MatissJanis** [comment]
Thanks!

**Pull request merged**
