### PR TITLE
[WIP] Update bank-factory.js and add Deutsche Kreditbank AG (DKB) (DKB_BYLADEM1) to the 90-days sync limited list

### PR DESCRIPTION
**Pull request by zenminimalist**
---
category: Enhancements
authors: [zenminimalist]
---
Update bank-factory.js and add Deutsche Kreditbank AG (DKB) (DKB_BYLADEM1) to the 90-days sync limited list

### CODE REVIEW

**Review by joshelboy — CHANGES_REQUESTED** [review]
To keep the code clean:
Please put the 'DKB...' in the right alphabetical order 😃
(Between COOP and DOTS)

**Comment by zenminimalist** [comment]
> To keep the code clean: Please put the 'DKB...' in the right alphabetical order 😃 (Between COOP and DOTS)

download

You're right. I'm sooo sorry. Fixed.  😅

**Comment by matt-fidd** [comment]
Hi! Thanks for this, you'll need to add a release note before I can merge it in.

https://actualbudget.com/docs/contributing/#writing-good-release-notes

**Comment by zenminimalist** [comment]
> Hi! Thanks for this, you'll need to add a release note before I can merge it in.
> 
> https://actualbudget.com/docs/contributing/#writing-good-release-notes

What's wrong with the one on the top of this post?

**Review by matt-fidd — APPROVED** [review]
Thank you, sorry - I missed your earlier comment

**Pull request merged**
