### PR TITLE
Add a password set/reset script

### PR DESCRIPTION
**Pull request by j-f1**
This allows a couple of new workflows:

- setting the password before deploying the server, so that you don’t have to worry about an attacker bootstrapping it before you can
  ```shellsession
  $ npm run reset-password
  It looks like you don’t have a password set yet. Let’s set one up now!
  Enter a password, then press enter: hunter2
  Enter the password again, then press enter: hunter2
  Password set!
  ```
- resetting the password without having to delete the server-files database (which includes the file list we would like to not have to delete!
  ```shellsession
  $ npm run reset-password
  It looks like you already have a password set. Let’s reset it!
  Enter a password, then press enter: hunter2
  Enter the password again, then press enter: hunter2
  Password changed!
  ```

### CODE REVIEW

**Comment by j-f1** [comment]
Fixing CodeQL error in #187.

**Comment by j-f1** [comment]
I’ll look into ways of obscuring the input (such as with `****`). I don’t want to do the UNIX-style approach of hiding the password entirely since I’m worried people who aren’t used to that will think that something is broken.

**Comment by j-f1** [comment]
Done!

**Review by MatissJanis — APPROVED** [review]
Very cool

**Comment by BloodyHellcat** [comment]
Sorry for that low knowledge level question.
But how do I use this command on a docker instance of Actual Budget?

Thanks in advance for your response.

**Pull request merged**
