### PR TITLE
Added documentation to run with docker on home server

### PR DESCRIPTION
**Pull request by JoaoGarrido**
Hi!

Really enjoyed Actual and wrote some documentation after deploying it on my home server.

Provided a .env file together with instructions on how to deploy it with docker-compose together with some changes to the README.md to make it easier.

I'm not a native english speaker, so feel free to improve it or ask for changes.

Thanks for open sourcing Actual!

### CODE REVIEW

**Comment by fazzer4x** [comment]
Great writeup on how to deploy your custom docker image.
Thanks for the compose file as well the .env. I'm sure these will evolve once this project expands. 

Is there a particular reason why you chose to build the docker image instead of just pulling it from the repo?

**Comment by JoaoGarrido** [comment]
Hi,
I'm happy to contribute! The project is awesome and although I'm not a web developer, I can help with documentation and docker/home server deployment stuff.

So I actually did not use a custom image, I used the repo image (the one recommended before in the README.md). 
I re-used the subtitle and maybe it's not really a good subtitle. I propose changing:

## Using a custom docker setup

To

## Using the repository docker image

**Comment by JoaoGarrido** [comment]
Fixed the data path variable on the docker-compose.yml and removed some docs from the README.md that are now available on the actual wiki

**Comment by rich-howell** [comment]
Hey @JoaoGarrido 

Thanks for this, we don't have a docs section inside actual anymore. I am going to go ahead and close this PR and migrate your changes into the [documentation](https://actualbudget.github.io/docs/Installing/Docker/).

Thank you so much for putting this together, will be really useful in the Actual Documentation. 

Cheers
Rich

**Comment by JoaoGarrido** [comment]
Thanks, already noticed and makes sense to me too! :)

**Pull request closed without merging**
